# Validation script for Weekly Seasonality Check

# Load the LWP-TRENDS functions
suppressWarnings({
    source("Example_Files/R/LWPTrends_v2502/LWPTrends_v2502.r")
})

# Read the data generated by the Python script
data <- read.csv("validation/03_Weekly_Seasonality_Check/validation_data.csv")
names(data) <- c("myDate", "RawValue")
data$myDate <- as.Date(data$myDate)

# --- Prepare the data for LWP-TRENDS ---
data$Censored <- FALSE
data$CenType <- "not"
data <- GetMoreDateInfo(data)

data$Month <- factor(weekdays(data$myDate, abbreviate = TRUE),
                     levels = c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"))
data$TimeIncr <- data$Month
data$Season <- data$Month

# --- Check for Seasonality ---
seasonality_result <- SeasonalityTest(data, ValuesToUse = "RawValue", TimeIncrMed = FALSE, UseMidObs = FALSE)
cat("--- LWP-TRENDS: Seasonality Check ---\n")
cat(sprintf("  P-value: %.4f\n", seasonality_result$pvalue))
cat(sprintf("  Seasonal: %s\n", seasonality_result$pvalue < 0.05))

# --- Run the seasonal trend analysis ---
# WORKAROUND: The LWP script has an internal bug when TimeIncrMed=FALSE is used with high-frequency
# data, incorrectly converting the 'Censored' column to a list. Since our data is not
# censored, we can safely reset the column to a logical vector before the final analysis.
data$Censored <- FALSE
result <- SeasonalTrendAnalysis(data, ValuesToUse = "RawValue", Year = "Year", TimeIncrMed = FALSE, UseMidObs = FALSE)

# --- Get LAWA Trend Classification ---
result$analyte <- "value"
classification <- AssignConfCat(result, CatType = "Direction")

# --- Print the key results ---
cat("\n--- LWP-TRENDS: Seasonal Trend Analysis Results (No Aggregation) ---\n")
cat(sprintf("  Classification: %s\n", classification))
cat(sprintf("  P-value: %.4f\n", result$p))
cat(sprintf("  Slope: %.4f (%.4f, %.4f)\n", result$AnnualSenSlope, result$Sen_Lci, result$Sen_Uci))
