# Validation script for Basic Trend Analysis

# Load the LWP-TRENDS functions
# Suppress warnings that can arise from sourcing the script
suppressWarnings({
    source("Example_Files/R/LWPTrends_v2502/LWPTrends_v2502.r")
})

# Read the data generated by the Python script
data <- read.csv("validation/01_Basic_Trend_Analysis/validation_data.csv")

# --- Prepare the data for LWP-TRENDS ---
names(data) <- c("Year", "RawValue")
data$myDate <- as.Date(paste(data$Year, "-01-01", sep=""))
data$Censored <- FALSE
data$CenType <- "not"
data <- GetMoreDateInfo(data)
data$TimeIncr <- data$Year

# --- Run the non-seasonal trend analysis ---
result <- NonSeasonalTrendAnalysis(data, ValuesToUse = "RawValue", Year = "Year")

# --- Get LAWA Trend Classification ---
# The AssignConfCat function requires an 'analyte' column to exist in the data frame.
result$analyte <- "value"
lawa_classification <- AssignConfCat(result, CatType = "Decrease", nCat = "Simple")

# --- Print the key results ---
cat("--- LWP-TRENDS Analysis Results ---\n")
cat(sprintf("  P-value: %.4f\n", result$p))
cat(sprintf("  Z-statistic: %.4f\n", result$Z))
cat(sprintf("  Slope: %.2f (%.2f, %.2f)\n", result$AnnualSenSlope, result$Sen_Lci, result$Sen_Uci))
cat(sprintf("  Trend Classification: %s\n", lawa_classification))
