# Validation script for Aggregation Example

# Load the LWP-TRENDS functions
suppressWarnings({
    source("Example_Files/R/LWPTrends_v2502/LWPTrends_v2502.r")
})

# Read the data generated by the Python script
data <- read.csv("validation/04_Aggregation_Example/validation_data.csv")
names(data) <- c("myDate", "RawValue")
data$myDate <- as.Date(data$myDate)

# --- Prepare the data for LWP-TRENDS ---
data$Censored <- FALSE
data$CenType <- "not"
data <- GetMoreDateInfo(data)

# The Python example uses a period of 12 for its seasonal test,
# which corresponds to monthly seasons.
data$TimeIncr <- data$Month
data$Season <- data$Month

# --- Run the seasonal trend analysis ---
# The default LWP-TRENDS behavior is to aggregate by the median ('ValueForTimeIncr').
# This is comparable to the Python script's `agg_method='median'`.
result <- SeasonalTrendAnalysis(data, ValuesToUse = "RawValue", Year = "Year")

# --- Get LAWA Trend Classification ---
result$analyte <- "value"
classification <- AssignConfCat(result, CatType = "Direction")

# --- Print the key results ---
cat("\n--- LWP-TRENDS: Seasonal Trend Analysis Results ---\n")
cat(sprintf("  Classification: %s\n", classification))
cat(sprintf("  P-value: %.4f\n", result$p))
cat(sprintf("  Slope: %.4f (%.4f, %.4f)\n", result$AnnualSenSlope, result$Sen_Lci, result$Sen_Uci))
