
import os
import numpy as np
import pandas as pd
import MannKenSen as mks
import textwrap
import io
from contextlib import redirect_stdout

def generate_readme():
    """
    Generates a comprehensive README.md file for Example 19, demonstrating
    visual diagnostics of trend plots.
    """
    # --- 1. Define Paths and Code Block ---
    output_dir = os.path.dirname(__file__)

    code_block = textwrap.dedent("""
        import numpy as np
        import pandas as pd
        import MannKenSen as mks
        import os

        # Common time vector for all scenarios
        n = 40
        t = pd.to_datetime(pd.date_range(start='1980-01-01', periods=n, freq='YE'))
        output_dir = '.' # Save plots in the current directory

        # --- Scenario 1: Clear Increasing Trend ---
        print("--- Scenario 1: Clear Increasing Trend ---")
        np.random.seed(1)
        x_clear = np.linspace(0, 10, n) + np.random.normal(0, 1.0, n)
        plot_path_clear = os.path.join(output_dir, 'clear_trend.png')
        result_clear = mks.trend_test(x_clear, t, plot_path=plot_path_clear)
        print(f"Result: {result_clear.classification} (p={result_clear.p:.4f})")

        # --- Scenario 2: No Trend ---
        print("\\n--- Scenario 2: No Trend ---")
        np.random.seed(2)
        x_none = np.zeros(n) + np.random.normal(0, 3.0, n)
        plot_path_none = os.path.join(output_dir, 'no_trend.png')
        result_none = mks.trend_test(x_none, t, plot_path=plot_path_none)
        print(f"Result: {result_none.classification} (p={result_none.p:.3f})")

        # --- Scenario 3: High Uncertainty ---
        print("\\n--- Scenario 3: High Uncertainty ---")
        np.random.seed(3)
        x_uncertain = np.linspace(0, 3, n) + np.random.normal(0, 5.0, n)
        plot_path_uncertain = os.path.join(output_dir, 'uncertain_trend.png')
        result_uncertain = mks.trend_test(x_uncertain, t, plot_path=plot_path_uncertain)
        print(f"Result: {result_uncertain.classification} (p={result_uncertain.p:.3f})")
    """)

    # --- 2. Execute the Code Block to Get Outputs ---
    f = io.StringIO()
    # Execute in the example's directory to save plots correctly
    original_dir = os.getcwd()
    os.chdir(output_dir)
    with redirect_stdout(f):
        exec(code_block, {'np': np, 'pd': pd, 'mks': mks, 'os': os})
    os.chdir(original_dir)
    output_str = f.getvalue().strip()

    # --- 3. Construct the README ---
    readme_content = f"""
# Example 19: Visual Diagnostics of Trend Plots

The trend plots generated by the `MannKenSen` package are a powerful tool for diagnosing and interpreting your trend analysis. By observing the data points, the Sen's slope line, and the confidence intervals, you can gain a much deeper understanding of the results.

This example showcases three common scenarios.

## The Python Script

The following script generates three different datasets and creates a trend plot for each one.

```python
{code_block}
```

## Command Output

Running the script produces the following summary output for each scenario:

```
{output_str}
```

## Visual Interpretation of Each Scenario

### 1. Clear Increasing Trend

![Clear Trend Plot](clear_trend.png)

**Interpretation:**
-   **Data Points:** The points clearly follow an upward trajectory over time.
-   **Sen's Slope (Solid Line):** The trend line has a steep, positive slope, visually confirming the increasing trend.
-   **Confidence Intervals (Dotted Lines):** The CI bands are relatively narrow and are entirely above a horizontal (zero-slope) line. This indicates high confidence that the true slope is positive and significantly different from zero.

### 2. No Trend

![No Trend Plot](no_trend.png)

**Interpretation:**
-   **Data Points:** The points are scattered randomly around a central value with no clear upward or downward movement.
-   **Sen's Slope (Solid Line):** The trend line is nearly horizontal, indicating a slope close to zero.
-   **Confidence Intervals (Dotted Lines):** The CI band is centered around the Sen's slope and clearly contains the zero-slope line. This means that a true slope of zero is a plausible value, confirming the "No Trend" result.

### 3. High Uncertainty

![Uncertain Trend Plot](uncertain_trend.png)

**Interpretation:**
-   **Data Points:** There might be a slight upward tendency, but the data is extremely noisy and scattered.
-   **Sen's Slope (Solid Line):** The trend line shows a slight positive slope, suggesting a weak increasing signal.
-   **Confidence Intervals (Dotted Lines):** The CI band is **very wide**. This indicates a high degree of uncertainty in the true value of the slope, caused by the high variability (noise) in the data. Although the calculated slope is positive, the CI band overlaps with zero, so we cannot confidently rule out the possibility of no trend. This leads to the "No Trend" classification.
"""

    # Write the README file
    readme_file_path = os.path.join(output_dir, 'README.md')
    with open(readme_file_path, 'w') as f:
        f.write(readme_content)

    print("Successfully generated README and plots for Example 19.")

if __name__ == '__main__':
    generate_readme()
