import numpy as np
import pandas as pd
import MannKenSen as mks
import sys
import os

# Define the output directory
output_dir = 'Examples/15_Regional_Trend_Analysis'
os.makedirs(output_dir, exist_ok=True)

# Define output file paths
output_file = os.path.join(output_dir, 'regional_analysis_output.txt')
# No plot is generated by the regional_test function itself.

# Redirect output to a file
with open(output_file, 'w') as f:
    original_stdout = sys.stdout
    sys.stdout = f

    # --- 1. Introduction ---
    print("### Example 15: Regional Trend Analysis ###")
    print("\nThis example demonstrates how to perform a regional trend test, which")
    print("aggregates the trend results from multiple individual sites to determine")
    print("if there is an overall trend across a region.")
    print("\nThis is useful for understanding the big picture and avoiding conclusions")
    print("based on potentially anomalous results from a single location.")
    print("-" * 60)

    # --- 2. Generate Synthetic Data for Multiple Sites ---
    # Create time series data for three different sites.
    sites = ['Site A', 'Site B', 'Site C']
    years = np.arange(2010, 2021)
    n_years = len(years)

    # Site A: Clear increasing trend
    trend_a = np.linspace(0, 5, n_years)
    noise_a = np.random.normal(0, 1, n_years)
    values_a = 10 + trend_a + noise_a

    # Site B: Weaker increasing trend
    trend_b = np.linspace(0, 2, n_years)
    noise_b = np.random.normal(0, 1, n_years)
    values_b = 15 + trend_b + noise_b

    # Site C: No clear trend (stable)
    trend_c = np.linspace(0, 0, n_years)
    noise_c = np.random.normal(0, 1, n_years)
    values_c = 12 + trend_c + noise_c

    # Combine into a single DataFrame
    df_a = pd.DataFrame({'site': 'Site A', 'year': years, 'value': values_a})
    df_b = pd.DataFrame({'site': 'Site B', 'year': years, 'value': values_b})
    df_c = pd.DataFrame({'site': 'Site C', 'year': years, 'value': values_c})
    regional_data = pd.concat([df_a, df_b, df_c], ignore_index=True)

    print("\n--- Generated Data ---")
    print("Created data for 3 sites:")
    print("- Site A: Strong Increasing Trend")
    print("- Site B: Weak Increasing Trend")
    print("- Site C: No Trend")
    print("\nData head:")
    print(regional_data.head().to_string())
    print("-" * 60)

    # --- 3. Perform Individual Trend Tests ---
    print("\n--- 3. Performing Trend Test for Each Site ---")
    print("First, we analyze each site individually to get its trend result.")
    site_results = []
    for site in sites:
        site_data = regional_data[regional_data['site'] == site]
        result = mks.trend_test(x=site_data['value'], t=site_data['year'])
        site_results.append(result)
        print(f"\n{site} Result:")
        print(result)
    print("-" * 60)

    # --- 4. Perform Regional Trend Test ---
    print("\n--- 4. Performing Regional Trend Test ---")
    print("Now, we combine the individual site results into a DataFrame and pass")
    print("it, along with the original time series data, to the `regional_test`")
    print("function to calculate the overall regional trend.")

    # Convert the list of namedtuple results into a DataFrame
    results_df = pd.DataFrame(site_results)
    results_df['site'] = sites # Add the site names

    regional_result = mks.regional_test(
        trend_results=results_df,
        time_series_data=regional_data,
        site_col='site',
        value_col='value',
        time_col='year',
        s_col='s', # Specify the column name for the S-statistic
        c_col='C'   # Specify the column name for the confidence
    )

    print("\nRegional Test Result:")
    print(regional_result)
    print("\nConclusion: Despite one site having no trend, the combined evidence")
    print(f"from the region points to an overall '{regional_result.DT}' trend.")
    print("-" * 60)

# Restore stdout
sys.stdout = original_stdout
print(f"Example 15 script finished. Output saved to {output_file}")
