import os
import pandas as pd
import numpy as np
import MannKenSen as mk

# rpy2 setup
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.packages import importr
from rpy2.robjects.conversion import localconverter

# --- 1. Data Generation ---
# Generate a dataset with a clear monthly seasonal pattern and an increasing trend.
np.random.seed(42)
n_years = 20
n = n_years * 12
t = pd.to_datetime(pd.date_range(start='2000-01-01', periods=n, freq='MS'))

# Trend component
slope = 0.8 / 12  # Slope per month
intercept = 15
trend = slope * np.arange(n) + intercept

# Seasonal component
seasonal = 5 * np.sin(2 * np.pi * np.arange(n) / 12)

# Noise component
noise = np.random.normal(0, 1.5, n)

# Combine components
x = trend + seasonal + noise

data = pd.DataFrame({
    'time': t,
    'value': x,
    'Censored': False,
    'CenType': 'not'
})

# --- Introduce Missing Season ---
# Remove all data for a specific month (e.g., July, month = 7)
month_to_remove = 7
data_missing = data[data['time'].dt.month != month_to_remove].copy()
x_missing = data_missing['value'].values
t_missing = data_missing['time'].values


csv_path = os.path.join(os.path.dirname(__file__), 'data.csv')
data_missing.to_csv(csv_path, index=False)


# --- 2. MannKenSen Analysis ---
plot_path = os.path.join(os.path.dirname(__file__), 'missing_season_plot.png')
mk_standard = mk.seasonal_trend_test(
    x_missing, t_missing,
    period=12,
    slope_scaling='year',
    alpha=0.1,
    plot_path=plot_path
)

mk_lwp = mk.seasonal_trend_test(
    x_missing, t_missing,
    period=12,
    slope_scaling='year',
    alpha=0.1,
    agg_method='lwp',
    ci_method='lwp'
)

# --- 3. R LWP-TRENDS Analysis ---
r_script_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../Example_Files/R/LWPTrends_v2502/LWPTrends_v2502.r'))
base = importr('base')
base.source(r_script_path)

data_missing['RawValue'] = data_missing['value']

with localconverter(ro.default_converter + pandas2ri.converter):
    r_data = ro.conversion.py2rpy(data_missing)

ro.globalenv['mydata'] = r_data
ro.r('mydata$myDate <- as.Date(mydata$time)')
ro.r('data_processed <- GetMoreDateInfo(mydata)')
ro.r('data_processed$Season <- data_processed$Month')
ro.r('data_processed$TimeIncr <- data_processed$Month')

try:
    r_results = ro.r('SeasonalTrendAnalysis(data_processed, ValuesToUse="RawValue", TimeIncrMed=TRUE)')

    with localconverter(ro.default_converter + pandas2ri.converter):
        r_results_df = ro.conversion.rpy2py(r_results)

    # Check for NULL, NA, or the specific large negative number indicating failure
    p_val = r_results_df['p'].iloc[0]
    if r_results_df is None or pd.isna(p_val) or p_val < -1e9:
        raise ValueError("R script returned NA or error code, indicating a failure.")

    r_p_value = f"{p_val:.6f}"
    r_slope = f"{r_results_df['AnnualSenSlope'].iloc[0]:.6f}"
    r_lower_ci = f"{r_results_df['Sen_Lci'].iloc[0]:.6f}"
    r_upper_ci = f"{r_results_df['Sen_Uci'].iloc[0]:.6f}"

except Exception as e:
    print(f"R script execution failed: {e}")
    r_p_value = "R Script Failed"
    r_slope = "R Script Failed"
    r_lower_ci = "R Script Failed"
    r_upper_ci = "R Script Failed"


# --- 4. Generate README Report ---
readme_content = f"""
# Validation Case V-11: Seasonal Data with Missing Seasons

## Objective
This test verifies that the `seasonal_trend_test` function can gracefully handle datasets where an entire season is missing, and compares this behavior to the LWP-TRENDS script.

## Data
A synthetic dataset of {n_years} years of monthly data was generated with a strong seasonal cycle and a clear increasing trend. Subsequently, all data points for a single month (July, month 7) were removed from the dataset.

The plot below, generated by `mannkensen`, shows the resulting time series. Note the consistent annual gap in the data where the July observations would be.

![Missing Season Plot](missing_season_plot.png)

## Results Comparison

| Metric              | MannKenSen (Standard) | MannKenSen (LWP Mode) | LWP-TRENDS R Script |
|---------------------|-----------------------|-----------------------|---------------------|
| p-value             | {mk_standard.p:.6f}   | {mk_lwp.p:.6f}        | {r_p_value}     |
| Sen's Slope (annual)| {mk_standard.slope:.6f} | {mk_lwp.slope:.6f}    | {r_slope}       |
| Lower CI (90%)      | {mk_standard.lower_ci:.6f} | {mk_lwp.lower_ci:.6f} | {r_lower_ci}    |
| Upper CI (90%)      | {mk_standard.upper_ci:.6f} | {mk_lwp.upper_ci:.6f} | {r_upper_ci}    |

## Analysis
The **`mannkensen` package** (in both Standard and LWP Mode) successfully processed the dataset despite the missing season. It correctly identified the significant underlying increasing trend by running the analysis on the 11 remaining seasons.

The **LWP-TRENDS R Script**, however, failed to produce a valid result. The script's internal logic does not appear to be robust to cases where an entire season is absent from the data, causing it to return NA values.

This validation case highlights a key robustness improvement in the `mannkensen` package over the original R script.
"""

readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
with open(readme_path, 'w') as f:
    f.write(readme_content.strip())

print("Validation V-11 complete. README.md generated.")
