"""
This script generates the guide for the regional_test function.
"""
import os
import textwrap

def generate_guide():
    """Generates the README.md file for this guide."""

    # 1. Define the Guide Content
    guide_content = """
    # A Comprehensive Guide to `regional_test`

    The `regional_test` function is a powerful tool for aggregating trend analysis results from multiple sites to determine if there is a consistent, region-wide trend. This guide explains its purpose, how to format your data, and how to interpret the results.

    ## Purpose of `regional_test`

    You should use `regional_test` when you have time series data from several different locations (sites) and you want to answer the question: "Is there an overall trend in this region?" The test is based on the Regional Kendall Test, which considers both the individual trend at each site and the correlation between the sites.

    ## Input Data Format

    The `regional_test` function requires two pandas DataFrames as input:

    1.  **`time_series_data`**: This DataFrame must contain the raw time series data for all sites. It needs the following columns, which can be renamed using the `site_col`, `time_col`, and `value_col` parameters:
        -   `site`: A unique identifier for each site.
        -   `time`: The timestamp or numeric time value for each observation.
        -   `value`: The data value of each observation.

    2.  **`trend_results`**: This DataFrame must contain the trend analysis results for each individual site, typically generated by running `trend_test` on each site's data. It needs the following columns, which can be renamed using the `site_col`, `s_col`, and `c_col` parameters:
        -   `site`: A unique identifier for each site, which must match the `site`s in `time_series_data`.
        -   `s`: The Mann-Kendall S-statistic for the site.
        -   `C`: The confidence of the trend direction for the site.

    ### Example Input DataFrames

    ```python
    # Example time_series_data
    #    site       time     value
    # 0     A 2000-01-01  5.1
    # 1     A 2001-01-01  5.3
    # 2     B 2000-01-01  7.8
    # 3     B 2001-01-01  7.5
    # ...

    # Example trend_results
    #   site         s         C
    # 0    A      15.0  0.95
    # 1    B     -12.0  0.92
    # ...
    ```

    ## Parameter Reference

    ### `trend_results`
    -   **Type:** `pandas.DataFrame`
    -   **Description:** The DataFrame containing the summary statistics (S-score and Confidence) for each site.

    ### `time_series_data`
    -   **Type:** `pandas.DataFrame`
    -   **Description:** The DataFrame containing the raw data for all sites. This is used to calculate the correlation between sites.

    ### `site_col`
    -   **Type:** `str`, **Default:** `'site'`
    -   **Description:** The name of the column containing unique site identifiers. This column must exist in **both** input DataFrames.

    ### `value_col`
    -   **Type:** `str`, **Default:** `'value'`
    -   **Description:** The name of the column in `time_series_data` containing the observed values.

    ### `time_col`
    -   **Type:** `str`, **Default:** `'time'`
    -   **Description:** The name of the column in `time_series_data` containing the timestamps.

    ### `s_col`
    -   **Type:** `str`, **Default:** `'s'`
    -   **Description:** The name of the column in `trend_results` containing the Mann-Kendall S-statistic.

    ### `c_col`
    -   **Type:** `str`, **Default:** `'C'`
    -   **Description:** The name of the column in `trend_results` containing the trend confidence value (0 to 1).

    ## Output Fields

    The function returns a `namedtuple` with the following fields:

    -   **`M`** (`int`): The total number of sites included in the analysis.
    -   **`TAU`** (`float`): The aggregate trend strength, which is the proportion of sites trending in the modal (most common) direction.
    -   **`VarTAU`** (`float`): The uncorrected variance of `TAU`.
    -   **`CorrectedVarTAU`** (`float`): The variance of `TAU` corrected for inter-site correlation.
    -   **`DT`** (`str`): The aggregate trend direction ('Increasing' or 'Decreasing').
    -   **`CT`** (`float`): The confidence in the aggregate trend direction, ranging from 0 to 1. A higher value indicates greater confidence.

    ## Example Usage

    Here is a simple example of how to use the function:

    ```python
    import pandas as pd
    from MannKS import regional_test, trend_test

    # 1. Create sample data for multiple sites
    sites = ['Site A', 'Site B', 'Site C']
    all_series_data = []
    all_trend_results = []

    for site in sites:
        time = pd.to_datetime(['2000', '2001', '2002', '2003', '2004'])
        value = (
            [1, 2, 3, 4, 5] if 'A' in site else
            [1.1, 2.1, 3.1, 4.1, 5.1] if 'B' in site else
            [5, 4, 3, 2, 1] # Decreasing trend
        )

        site_df = pd.DataFrame({'site': site, 'time': time, 'value': value})
        all_series_data.append(site_df)

        # 2. Run trend_test for each site
        result = trend_test(x=site_df['value'], t=site_df['time'])
        all_trend_results.append({
            'site': site,
            's': result.s,
            'var_s': result.var_s, # Note: var_s is needed for individual tests, but not for regional_test
            'C': result.C
        })

    time_series_df = pd.concat(all_series_data).reset_index(drop=True)
    trend_results_df = pd.DataFrame(all_trend_results)

    # 3. Run the regional test
    regional_result = regional_test(
        time_series_data=time_series_df,
        trend_results=trend_results_df,
        site_col='site' # Specify the site column name if different from 'site'
    )

    print(regional_result)
    ```
    """

    # 2. Write the README file
    readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
    with open(readme_path, 'w') as f:
        f.write(textwrap.dedent(guide_content))

    print("Successfully generated README for the regional_test guide.")

if __name__ == '__main__':
    generate_guide()
