"""
This script generates the guide for the regional_test function.
"""
import os
import textwrap

def generate_guide():
    """Generates the README.md file for this guide."""

    # 1. Define the Guide Content
    guide_content = """
    # A Comprehensive Guide to `regional_test`

    The `regional_test` function is a powerful tool for aggregating trend analysis results from multiple sites to determine if there is a consistent, region-wide trend. This guide explains its purpose, how to format your data, and how to interpret the results.

    ## Purpose of `regional_test`

    You should use `regional_test` when you have time series data from several different locations (sites) and you want to answer the question: "Is there an overall trend in this region?" The test is based on the Regional Kendall Test, which considers both the individual trend at each site and the correlation between the sites.

    ## Input Data Format

    The `regional_test` function requires two pandas DataFrames as input:

    1.  **`time_series_data`**: This DataFrame must contain the raw time series data for all sites. It needs the following columns:
        -   `site_id`: A unique identifier for each site.
        -   `time`: The timestamp or numeric time value for each observation.
        -   `value`: The data value of each observation.

    2.  **`trend_results`**: This DataFrame must contain the trend analysis results for each individual site, typically generated by running `trend_test` on each site's data. It needs the following columns:
        -   `site_id`: A unique identifier for each site, which must match the `site_id`s in `time_series_data`.
        -   `s`: The Mann-Kendall S-statistic for the site.
        -   `var_s`: The variance of the S-statistic for the site.

    ### Example Input DataFrames

    ```python
    # Example time_series_data
    #    site_id       time     value
    # 0        A 2000-01-01  5.1
    # 1        A 2001-01-01  5.3
    # 2        B 2000-01-01  7.8
    # 3        B 2001-01-01  7.5
    # ...

    # Example trend_results
    #   site_id         s     var_s
    # 0       A  15.0  250.0
    # 1       B -12.0  245.0
    # ...
    ```

    ## Output Fields

    The function returns a `namedtuple` with the following fields:

    -   **`DT`** (`str`): The direction of the regional trend. Possible values are `'Increasing'`, `'Decreasing'`, or `'No Clear Direction'`.
    -   **`p_value`** (`float`): The p-value for the regional trend test. A small p-value (e.g., ≤ 0.05) indicates that the regional trend is statistically significant.
    -   **`z_stat`** (`float`): The Z-statistic for the overall regional trend.
    -   **`n_sites`** (`int`): The number of sites included in the analysis.
    -   **`n_increasing`** (`int`): The number of sites with an increasing trend.
    -   **`n_decreasing`** (`int`): The number of sites with a decreasing trend.
    -   **`S_total`** (`float`): The sum of the individual S-statistics from all sites.

    ## Example Usage

    Here is a simple example of how to use the function:

    ```python
    import pandas as pd
    from MannKenSen import regional_test, trend_test

    # 1. Create sample data
    sites = ['Site A', 'Site B', 'Site C']
    all_series_data = []
    all_trend_results = []

    for site in sites:
        # In a real scenario, you would have your own data here
        time = pd.to_datetime(['2000', '2001', '2002', '2003', '2004'])
        # Create some noisy data with a slight trend
        value = (
            [1, 2, 3, 4, 5] if 'A' in site else
            [5, 4, 3, 2, 1] if 'B' in site else
            [1, 3, 2, 5, 4] # No clear trend
        )

        site_df = pd.DataFrame({'site_id': site, 'time': time, 'value': value})
        all_series_data.append(site_df)

        # 2. Run trend_test for each site
        result = trend_test(x=site_df['value'], t=site_df['time'])
        all_trend_results.append({
            'site_id': site,
            's': result.s,
            'var_s': result.var_s
        })

    time_series_df = pd.concat(all_series_data).reset_index(drop=True)
    trend_results_df = pd.DataFrame(all_trend_results)

    # 3. Run the regional test
    regional_result = regional_test(
        time_series_data=time_series_df,
        trend_results=trend_results_df,
        time_col='time',
        value_col='value',
        site_id_col='site_id'
    )

    print(regional_result)
    ```
    """

    # 2. Write the README file
    readme_path = os.path.join(os.path.dirname(__file__), 'README.md')
    with open(readme_path, 'w') as f:
        f.write(textwrap.dedent(guide_content))

    print("Successfully generated README for the regional_test guide.")

if __name__ == '__main__':
    generate_guide()
