
import os
import numpy as np
import pandas as pd
import MannKenSen

def generate_readme():
    """
    Generates the README.md file for this example by creating and analyzing
    three different datasets to showcase visual diagnostics.
    """
    # Common time vector for all scenarios
    n = 40
    t = pd.to_datetime(pd.date_range(start='1980-01-01', periods=n, freq='YE'))

    # --- Scenario 1: Clear Increasing Trend ---
    np.random.seed(1)
    x_clear = np.linspace(0, 10, n) + np.random.normal(0, 1.0, n)
    plot_path_clear = os.path.join(os.path.dirname(__file__), 'clear_trend.png')
    result_clear = MannKenSen.trend_test(x_clear, t, plot_path=plot_path_clear)

    # --- Scenario 2: No Trend ---
    np.random.seed(2)
    x_none = np.zeros(n) + np.random.normal(0, 3.0, n)
    plot_path_none = os.path.join(os.path.dirname(__file__), 'no_trend.png')
    result_none = MannKenSen.trend_test(x_none, t, plot_path=plot_path_none)

    # --- Scenario 3: High Uncertainty ---
    np.random.seed(3)
    x_uncertain = np.linspace(0, 3, n) + np.random.normal(0, 5.0, n)
    plot_path_uncertain = os.path.join(os.path.dirname(__file__), 'uncertain_trend.png')
    result_uncertain = MannKenSen.trend_test(x_uncertain, t, plot_path=plot_path_uncertain)

    # --- Generate README ---
    readme_content = f"""
# Example 19: Visual Diagnostics of Trend Plots

The trend plots generated by the `MannKenSen` package are a powerful tool for diagnosing and interpreting your trend analysis. By observing the data points, the Sen's slope line, and the confidence intervals, you can gain a much deeper understanding of the results.

This example showcases three common scenarios.

## 1. Clear Increasing Trend

**Result:** `{result_clear.classification}` (p={result_clear.p:.4f})

![Clear Trend Plot](clear_trend.png)

**Interpretation:**
-   **Data Points:** The points clearly follow an upward trajectory over time.
-   **Sen's Slope (Solid Line):** The trend line has a steep, positive slope, visually confirming the increasing trend.
-   **Confidence Intervals (Dotted Lines):** The CI bands are relatively narrow and are entirely above a horizontal (zero-slope) line. This indicates high confidence that the true slope is positive and significantly different from zero.

## 2. No Trend

**Result:** `{result_none.classification}` (p={result_none.p:.3f})

![No Trend Plot](no_trend.png)

**Interpretation:**
-   **Data Points:** The points are scattered randomly around a central value with no clear upward or downward movement.
-   **Sen's Slope (Solid Line):** The trend line is nearly horizontal, indicating a slope close to zero.
-   **Confidence Intervals (Dotted Lines):** The CI band is centered around the Sen's slope and clearly contains the zero-slope line. This means that a true slope of zero is a plausible value, confirming the "No Trend" result.

## 3. High Uncertainty

**Result:** `{result_uncertain.classification}` (p={result_uncertain.p:.3f})

![Uncertain Trend Plot](uncertain_trend.png)

**Interpretation:**
-   **Data Points:** There might be a slight upward tendency, but the data is extremely noisy and scattered.
-   **Sen's Slope (Solid Line):** The trend line shows a slight positive slope, suggesting a weak increasing signal.
-   **Confidence Intervals (Dotted Lines):** The CI band is **very wide**. This indicates a high degree of uncertainty in the true value of the slope, caused by the high variability (noise) in the data. Although the calculated slope is positive, the CI band overlaps with zero, so we cannot confidently rule out the possibility of no trend. This leads to the "No Trend" classification.
"""

    # Write to file
    filepath = os.path.join(os.path.dirname(__file__), 'README.md')
    with open(filepath, 'w') as f:
        f.write(readme_content)
    print("Generated README.md and plots for Example 19.")

if __name__ == '__main__':
    generate_readme()
