# Load required libraries
library(plyr)
library(tidyr)
library(viridis)
library(NADA)
library(lubridate)
library(gam)
library(ggplot2)
library(ggpubr)

# Load the LWP-TRENDS functions
source("Example_Files/R/LWPTrends_v2502/LWPTrends_v2502.r")

# --- Main Validation Script ---

# 1. Load Data
# The CSV is generated by the Python script and contains 'time' and 'value' columns.
data <- read.csv("validation/02_Censored_Seasonal_Trend/validation_data.csv")

# 2. Prepare Data for LWP-TRENDS functions
# The R functions expect specific column names and data types.
data$myDate <- as.Date(paste0(floor(data$time), "-", round((data$time %% 1) * 12) + 1, "-01")) # Convert fractional year to Date
data$Value <- as.character(data$value) # Ensure the value column is character for parsing

# 3. Pre-process Censored Data
# This function parses strings like "<35" into numeric and censoring columns.
data_processed <- RemoveAlphaDetect(data, ColToUse = "Value")

# 4. Add Date Information
# This function adds Year, Month, etc., which are required by the analysis function.
data_with_dates <- GetMoreDateInfo(data_processed)

# 5. Run Seasonal Trend Analysis
# We use settings that align with the Python script's 'lwp' method.
# The `doMyTrends_v2502` function is a wrapper that will perform the seasonal test.
# We set the TimeIncrOpts to "Monthly" to match the period=12 in Python.
result <- doMyTrends_v2502(
  data_with_dates,
  ValuesToUse = "RawValue",
  TimeIncrOpts = "Monthly"
)

# 6. Print R Results for Comparison
# We format the output to match the Python script's output for easy comparison.
cat("\n--- R LWP-TRENDS Package Results ---\n")
if (!is.null(result)) {
  cat(paste0("  Trend Direction: ", result$TrendDirection, "\n"))
  cat(paste0("  P-value: ", sprintf("%.4f", result$p), "\n"))
  cat(paste0("  Annual Sen Slope: ", sprintf("%.4f", result$AnnualSenSlope), "\n"))
  cat(paste0("  Lower CI: ", sprintf("%.4f", result$Sen_Lci), "\n"))
  cat(paste0("  Upper CI: ", sprintf("%.4f", result$Sen_Uci), "\n"))
  cat(paste0("  Analysis Note: ", ifelse(is.na(result$AnalysisNote), "None", result$AnalysisNote), "\n"))
} else {
  cat("  Analysis could not be completed.\n")
}
